
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import { ToasterContext } from "@/context/HotToaster";
const inter = Inter({ subsets: ["latin"] });
import { cookies } from "next/headers";


export const metadata: Metadata = {
  title: "Flight App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = cookies().get("accessToken");
  return (
    <html lang="en">
      <body className='w-full mx-auto'>
        {/* <Providers> */}
          <ToasterContext />
          <Navbar user={user} />
          {children}
        {/* </Providers> */}
      </body>
    </html>
  );
}
